<<<<<<< HEAD
module CONTROLPATH (CLK, RSTn, CLEAR_N, READ, WRITE, F_FULL_N, F_EMPTY_N, USE_DW);
input	CLK, RSTn, CLEAR_N. READ, WRITE;
output F_FULL_N, F_EMPTY_N, USE_DW; 
=======
module CONTROLPATH (CLK, RSTn, CLEAR_N, READ, WRITE, F_FULL_N, F_EMPTY_N, USE_DW);
input	CLK, RSTn, CLEAR_N. READ, WRITE;
output F_FULL_N, F_EMPTY_N, USE_DW; 
>>>>>>> e99947d70da2da51086db8548407630d59b0de8b
	